<?php

/**
 * @file
 * 
 * Provides JSON data on SimpleAds.
 */

/**
 * Implements hook_menu().
 */
function simpleads_json_menu() {
  return array(
    'simpleads/json' => array(
      'page callback' => 'simpleads_json_output',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Page Callback.
 * 
 * @return type json mixed
 *   JSON result related to query
 */
function simpleads_json_output() {
  
  $output = '';
  
  $date = array(
    'start' => isset($_GET['start']) ? $_GET['start'] : '',
    'end' => isset($_GET['end']) ? $_GET['end'] : '',
  );
  
  $valid = (isset($_GET['start']) && _simpleads_json_check_format($date))
      ? TRUE : FALSE;
  
  switch ($valid) {
    case TRUE:

      $output = drupal_json_output(_simpleads_json_query_result($date));
      break;
    case FALSE:
      
        $output = drupal_json_output(array('error' => 'invalid request',));
      break;
  }
  
  return $output;
}

/**
 * Check supplied date format.
 * 
 * @param type $date array mixed
 *  contains start date and probably end date.
 * 
 * @return type boolean
 *   - TRUE
 *      if date format is correct.
 *   - FALSE
 *      if date format is incorrect. 
 */
function _simpleads_json_check_format($date) {
 
  return ($date['end'] != '') ? 
    ((((DateTime::createFromFormat('Y-m-d', $date['start']) !== FALSE)
      && DateTime::createFromFormat('Y-m-d', $date['end']) !== FALSE)) ?
        TRUE : FALSE) : 
    ((DateTime::createFromFormat('Y-m-d', $date['start']) !== FALSE) ?
      TRUE : FALSE);
}

/**
 * Returns the fetched query from database.
 * 
 * @param type $date array mixed
 *   start date and probably end date 
 * 
 * @return type array mixed
 *   an array contaning information on published ads.
 */
function _simpleads_json_query_result($date) {
  
  $node = array('title', 'nid', 'status');
  
  $field_ad_date = array('field_ad_date_value', 'field_ad_date_value2');
  
  $query = db_select('node', 'n');
  $query->join('field_data_field_ad_date', 'd', 'n.nid = d.entity_id');
  $query->fields('n', $node)
      ->fields('d', $field_ad_date)
      ->condition('d.field_ad_date_value', $date['start'], '>=');
  if($date['end'] != '') {
    $query->condition('d.field_ad_date_value2', $date['end'], '<=');
  }
  $query->orderBy('n.nid');
  
  return $query->execute()->fetchall();
}