<?php

/**
 * @file
 * 
 * Provides JSON data on SimpleAds.
 */

/**
 * Implements hook_menu().
 */
function simpleads_json_menu() {
  return array(
    'simpleads/json' => array(
      'page callback' => 'simpleads_json_output',
      'access arguments' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

function simpleads_json_output() {
  
  $output = '';
  
  $date = array(
    'start' => isset($_GET['start']) ? $_GET['start'] : '',
    'end' => isset($_GET['end']) ? $_GET['end'] : '',
  );
  
  $valid = (isset($_GET['start']) && _simpleads_json_check_format($date))
      ? TRUE : FALSE;
  
  switch ($valid) {
    case TRUE:
        $output = drupal_json_output(array('start' => $_GET['start'],));
      break;
    case FALSE:
        $output = drupal_json_output(array('error' => 'invalid request',));
      break;
  }
  
  return $output;
}

/**
 * Check supplied date format.
 * 
 * @param type $date array mixed
 *  contains start date and probably end date.
 * 
 * @return type boolean
 *   - TRUE
 *      if date format is correct.
 *   - FALSE
 *      if date format is incorrect. 
 */
function _simpleads_json_check_format($date) {
 
  return ($date['end'] != '') ? 
    ((((DateTime::createFromFormat('m/d/Y', $date['start']) !== FALSE)
      && DateTime::createFromFormat('m/d/Y', $date['end']) !== FALSE)) ?
        TRUE : FALSE) : 
    ((DateTime::createFromFormat('m/d/Y', $date['start']) !== FALSE) ?
      TRUE : FALSE);
}